spring.datasource.url=jdbc:postgresql://neondb_owner:npg_UYae1dVT8rkA@ep-snowy-mud-axu9mx04-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true